apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: unity-iscsi-snapshot
  namespace: unityiscsi
spec:
  volumeSnapshotClassName: unity-snap
  source:
    persistentVolumeClaimName: dynamic-iscsi-unity-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unity-iscsi-snapshot-pvc
  namespace: unityiscsi
spec:
  storageClassName: unity-iscsi
  dataSource:
    name: unity-iscsi-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: unity-iscsi-snapshot-pod
  namespace: unityiscsi
spec:
  imagePullSecrets:
  - name: docker
  containers:
  - name: task-pv-container
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/mnt"
        name: iscsi
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
  volumes:
    - name: iscsi
      persistentVolumeClaim:
        claimName: unity-iscsi-snapshot-pvc
