apiVersion: v1
kind: Pod
metadata:
  name: dynamic-nfs-isilon-pod
  namespace: isilon
spec:
  containers:
  - name: task-pv-container
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/mnt"
        name: dy-nfs-isilon
    command: ["/bin/bash", "-c", "sleep 2000000000"]
  nodeSelector:
    kubernetes.io/hostname: ipi-w1.dcws.lab
  volumes:
    - name: dy-nfs-isilon
      persistentVolumeClaim:
        claimName: dynamic-nfs-isilon-pvc
