apiVersion: v1
kind: Pod
metadata:
  name: restore-pod
  namespace: powermax
spec:
  containers:
  - name: task-pv-container
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/home"
        name: restore-pvc
    command: ["/bin/bash", "-c", "sleep 2000000000"]
  nodeSelector:
    kubernetes.io/hostname: ipi-w1.dcws.lab
  volumes:
    - name: restore-pvc
      persistentVolumeClaim:
        claimName: powermax-restore
