apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powermax-iscsi-pvc
  namespace: powermax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: powermaxsc-iscsi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
  namespace: powermax
data:
  sample: file data
---
apiVersion: v1
kind: Pod
metadata:
  name: powermax-iscsi-pod
  namespace: powermax
spec:
  containers:
  - name: task-pv-container
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/mnt"
        name: iscsi
      - mountPath: "/tmp"
        name: confmap
    command: ["/bin/bash", "-c", "sleep 2000000000"]
  nodeSelector:
    kubernetes.io/hostname: compute-1.dcws.lab
  volumes:
    - name: iscsi
      persistentVolumeClaim:
        claimName: powermax-iscsi-pvc
    - name: confmap
      configMap:
        name: demo
        items:
        - key: sample
          path: keys
