apiVersion: v1
kind: Namespace
metadata:
  name: powermax
---
apiVersion: v1
kind: Secret
metadata:
  name: powermax-creds
  namespace: powermax
type: Opaque
data:
  # specify base64 creds to unisphere
  username: <base64 contents of username>
  password: <base64 contents of password>
