---
# tasks file for dhcp
- name: install dhcp server
  yum:
    name: dhcp-server
    state: latest

- name: add firewalld service for dhcp
  firewalld:
    service: dhcp
    permanent: yes
    immediate: yes
    state: enabled

- name: set dns ip
  set_fact:
    dns_ip_address: "{% if dns_ip is defined %}{{ dns_ip }}{% elif vip is defined %}{{ vip }}{% else %}{{ ansible_default_ipv4.address }}{% endif %}"

- debug:
    msg: "{{ dns_ip_address }}"

- name: generate dhcpd config
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: "restart dhcp"

- name: enable and start dhcpd service
  systemd:
    name: dhcpd
    enabled: yes
    state: started
