---
apiVersion: v1
kind: Service
metadata:
  name: svs-sts-busybox
  labels:
    app: sts-busybox
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: sts-busybox
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-busybox
  labels:
    app: sts-busybox
spec:
  serviceName: "svc-sts-busybox"
  selector:
    matchLabels:
      app: sts-busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: sts-busybox
    spec:
      containers:
      - name: busybox
        image: registry.k8s.io/busybox
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: [ "sh", "-c" ]
        args: [ "while true; do echo $(date):$NODE_NAME:$POD_NAME >> /data/datafile; sleep 1; done;" ]
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 8Gi
      storageClassName: dellcsi-powerstore-sc 
