apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
  namespace: csi-baremetal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-csi
subjects:
- kind: ServiceAccount
  name: csi-baremetal-extender-sa
  namespace: csi-baremetal
- kind: ServiceAccount
  name: csi-node-sa
  namespace: csi-baremetal
