DISTRIBUTED_STORAGE_CONFIG:
  radosGWStorage:
    - RadosGWStorage
    - access_key: 1_root_accid
      secret_key: *****
      bucket_name: quay-bucket
      hostname: powers.dcws.lab
      is_secure: false
      port: '9021'
      storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - radosGWStorage

