apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: storage-config-bundle-secret
  components:
    - kind: objectstorage
      managed: false
