- hosts: primary
  become: yes
  roles:
    - http
    - dhcp
    - dns
    - proxy
    - ignition
    - pxe
    - bootstrap
- hosts: secondary
  become: yes
  roles:
    - http
    - dns
    - proxy
    - ignition
    - pxe
