apiVersion: v1
kind: Pod
metadata:
  name: aws-pod
  namespace: test
spec:
  containers:
  - name: aws
    image: amazon/aws-cli 
    ports:
      - containerPort: 80
        name: "aws"
    command: ["/bin/bash", "-c", "sleep 2000000000"]
