---
apiVersion: v1 
kind: Secret
metadata:
 name: openshift-worker-2-network-config-secret 
 namespace: openshift-machine-api
type: Opaque
stringData:
 nmstate: | 
  interfaces: 
  - name: bond0
    type: bond
    state: up
    ipv4:
      address:
      - ip: 192.168.32.69
        prefix-length: 24
      enabled: true
    link-aggregation:
      mode: 802.3ad
      port:
      - ens6f0
      - ens6f1
  dns-resolver:
    config:
      server:
      - 192.168.32.65
  routes:
    config:
    - destination: 0.0.0.0/0
      next-hop-address: 192.168.32.1
      next-hop-interface: bond0
---
apiVersion: v1
kind: Secret
metadata:
  name: openshift-worker-2-bmc-secret 
  namespace: openshift-machine-api
type: Opaque
data:
  username: cm9vdA==
  password: Y2Fsdmlu
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ipi-ans-8023ad-w2
  namespace: openshift-machine-api
spec:
  online: True
  bootMACAddress: 10:70:FD:F5:D6:68
  bmc:
    address: idrac-virtualmedia://172.16.0.69/redfish/v1/Systems/System.Embedded.1 
    credentialsName: openshift-worker-2-bmc-secret 
    disableCertificateVerification: True 
    username: root
    password: calvin
  rootDeviceHints:
    deviceName: /dev/nvme0n1
  preprovisioningNetworkDataName: openshift-worker-2-network-config-secret 
