apiVersion: v1
kind: Pod
metadata:
  name: odf-cephfs-pod
  namespace: odf-test
spec:
  containers:
  - name: ocs
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    command: ["/bin/bash", "-c", "sleep 2000000000"]
    volumeMounts:
      - mountPath: /data
        name: odf-cephfs-pod-pv
  volumes:
    - name: odf-cephfs-pod-pv
      persistentVolumeClaim:
        claimName: odf-cephfs-pod-pvc

