kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: odf-rbd-pvc
  namespace: odf-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Block
