kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ocs-ds-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
