apiVersion: v1
kind: Pod
metadata:
  name: odf-rbd-pod
  namespace: odf-test
spec:
  containers:
  - name: odf-rbd-container
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    command: ["/bin/bash", "-c", "sleep 2000000000"]
  volumes:
    - name: odf-rbd-pvc
      persistentVolumeClaim:
        claimName: odf-rbd-pvc

