---
apiVersion: v1
data:
  username: <base64 encoded username_of_unisphere>
  password: <base64 encoded password_of_unisphere>
kind: Secret
metadata:
  name: powermax-creds
  namespace: powermax
  type: Opaque
