apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powermax-iscsi-pvc
  namespace: powermax
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: powermaxsc-iscsi

