apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-hostpath-snap-isilon
driver: csi-isilon.dellemc.com
deletionPolicy: Delete

---

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: isilon-snapshot
  namespace: isilon
spec:
  volumeSnapshotClassName: csi-hostpath-snap-isilon
  source:
    persistentVolumeClaimName: dynamic-nfs-isilon-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isilon-restore
spec:
  storageClassName: isilon-sc
  dataSource:
    name: isilon-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: restore-pods
  namespace: isilon
spec:
  containers:
  - name: task-pv-container
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/mnt/snapshot"
        name: restore-pvc
    command: ["/bin/bash", "-c", "sleep 2000000000"]
  nodeSelector:
    kubernetes.io/hostname: compute-1.dcws.lab
  volumes:
    - name: restore-pvc
      persistentVolumeClaim:
        claimName: isilon-restore

