apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-replication
  namespace: isilon
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: isilon-replication
