---
- hosts: all
  connection: local
  name: Power servers off
  gather_facts: False

  tasks:
  - name: Configure Server Power Setting
    dellemc_change_power_state:
       idrac_ip:   "{{ idrac_ip }}"
       idrac_user: "{{ user }}"
       idrac_pwd:  "{{ password }}"
       change_power: "GracefulShutdown"
