apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
  namespace: powerstore
data:
  sample: file data
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: powerstore
spec:
  containers:
  - name: task-pv-container
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/mnt"
        name: vol
      - mountPath: "/tmp"
        name: confmap
    command: ["/bin/bash", "-c", " sleep 2000000000"]
  nodeName: etcd1.dcws.lab
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: powerstore-pvc-iscsi
    - name: confmap
      configMap:
        name: demo
        items:
        - key: sample
          path: keys

