---
# handlers file for pxe
- name: restart dhcp service
  systemd:
    name: dhcpd
    state: restarted
  listen: "restart dhcp"

- name: restart tftp
  systemd:
    name: tftp
    state: restarted
  listen: "restart tftp"

- name: reload systemd
  systemd:
    daemon_reload: yes   
  
