apiVersion: storage.dell.com/v1
kind: CSIPowerStore
metadata:
  name: powerstore-cr
  namespace: powerstore
spec:
  driver:
    # Config version for CSI PowerStore v2.3.0 driver
    configVersion: v2.3.0
    # Controller count
    replicas: 2
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    common:
      # Image for CSI PowerStore driver v2.3.0
      image: "dellemc/csi-powerstore:v2.3.0"
      imagePullPolicy: IfNotPresent
      envs:
        - name: X_CSI_POWERSTORE_NODE_NAME_PREFIX
          value: "csi"
#        - name: X_CSI_FC_PORTS_FILTER_FILE_PATH
#          value: "/etc/fc-ports-filter"
        - name: X_CSI_TRANSPORT_PROTOCOL
          value: "iscsi"
    controller:
      envs:
        # X_CSI_NFS_ACLS: enables setting permissions on NFS mount directory
        # This value will be the default value if a storage class and array config in secret
        # do not contain the NFS ACL (nfsAcls) parameter specified
        # Permissions can be specified in two formats:
        #   1) Unix mode (NFSv3)
        #   2) NFSv4 ACLs (NFSv4)
        #      NFSv4 ACLs are supported on NFSv4 share only.
        # Allowed values:
        #   1) Unix mode: valid octal mode number
        #      Examples: "0777", "777", "0755"
        #   2) NFSv4 acls: valid NFSv4 acls, seperated by comma
        #      Examples: "A::OWNER@:RWX,A::GROUP@:RWX", "A::OWNER@:rxtncy"
        # Optional: true
        # Default value: "0777"
        # nfsAcls: "0777"
        - name: X_CSI_NFS_ACLS
          value: "0777"

      # nodeSelector: Define node selection constraints for controller pods.
      # For the pod to be eligible to run on a node, the node must have each
      # of the indicated key-value pairs as labels.
      # Leave as blank to consider all nodes
      # Allowed values: map of key-value pairs
      # Default value: None
      nodeSelector:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      #  node-role.kubernetes.io/master: ""
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      #  node-role.kubernetes.io/control-plane: ""

      # tolerations: Define tolerations for the controllers, if required.
      # Leave as blank to install controller on worker nodes
      # Default value: None
      tolerations:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      # - key: "node-role.kubernetes.io/master"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      # - key: "node-role.kubernetes.io/control-plane"
      #   operator: "Exists"
      #   effect: "NoSchedule"
    node:
      envs:
        # Set to "true" to enable ISCSI CHAP Authentication
        # CHAP password will be autogenerated by driver
        - name: "X_CSI_POWERSTORE_ENABLE_CHAP"
          value: "false"

      # nodeSelector: Define node selection constraints for node pods.
      # For the pod to be eligible to run on a node, the node must have each
      # of the indicated key-value pairs as labels.
      # Leave as blank to consider all nodes
      # Allowed values: map of key-value pairs
      # Default value: None
      nodeSelector:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      #  node-role.kubernetes.io/master: ""
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      #  node-role.kubernetes.io/control-plane: ""

      # tolerations: Define tolerations for the controllers, if required.
      # Leave as blank to install controller on worker nodes
      # Default value: None
      tolerations:
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/master taint
      # - key: "node-role.kubernetes.io/master"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # Uncomment if nodes you wish to use have the node-role.kubernetes.io/control-plane taint
      # - key: "node-role.kubernetes.io/control-plane"
      #   operator: "Exists"
      #   effect: "NoSchedule"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: powerstore-config-params
  namespace: powerstore
data:
  driver-config-params.yaml: |
    CSI_LOG_LEVEL: "debug"
    CSI_LOG_FORMAT: "JSON"
