apiVersion: v1
kind: Namespace
metadata:
  name: powerstore
---
apiVersion: v1
kind: Secret
metadata:
  name: powerstore-creds
  namespace: powerstore
type: Opaque
data:
  # specify the base64 contens of username and password to unisphere
  username: <base64 contents of username>
  password: <base64 contents of password>
  # Keys chapuser, chapsecret must be left blank if not used.
  chapuser:
  chapsecret:
