apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: powerstore-snap-class
driver: csi-powerstore.dellemc.com
deletionPolicy: Delete

---

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: powerstore-snapshot
spec:
  volumeSnapshotClassName: powerstore-snap-class
  source:
    persistentVolumeClaimName: powerstore-pvc-iscsi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerstore-restore
spec:
  storageClassName: dellcsi-powerstore-sc
  dataSource:
    name: powerstore-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: restore-pod
  namespace: powerstore
spec:
  containers:
  - name: task-pv-container
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/home"
        name: restore-pvc
    command: ["/bin/bash", "-c", "sleep 2000000000"]
  nodeSelector:
    kubernetes.io/hostname: compute-1.dcws.lab
  volumes:
    - name: restore-pvc
      persistentVolumeClaim:
        claimName: powerstore-restore
