apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-nfs-isilon-pvc
  namespace: isilon
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: isilon-sc

---

apiVersion: v1
kind: Pod
metadata:
  name: isilon-nfs-pod
  namespace: isilon
spec:
  containers:
  - name: task-pv-container
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/mnt"
        name: dy-nfs-isilon
    command: ["/bin/bash", "-c", "sleep 2000000000"]
  nodeSelector:
    kubernetes.io/hostname: compute-3.dcws.lab
  volumes:
    - name: dy-nfs-isilon
      persistentVolumeClaim:
        claimName: dynamic-nfs-isilon-pvc
