apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerstore-nfs-pvc
  namespace: powerstore
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: powerstore-sc-nfs
