# PerformanceProfile for real time kernel
# Using SMT
# Hardware Used: PowerEdge XE2420 Servers
apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: xe2420-performanceprofile
spec:
  additionalKernelArgs:
    - nmi_watchdog=0
    - audit=0
    - mce=off
    - processor.max_cstate=1
    - idle=poll
    - intel_idle.max_cstate=0
  cpu:
    isolated: "1,3-47,49,51,53-94"
    reserved: "0,48,2,50,4,52"
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - size: "1G"
      count: 16
  realTimeKernel:
    enabled: true
  numa:
    topologyPolicy: "restricted"
    # topologyPolicy: "best-effort" # May change performance, but this can be used
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""