apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: powerstore-snapshot
spec:
  volumeSnapshotClassName: powerstore-snap-class
  source:
    persistentVolumeClaimName: powerstore-nfs-pvc
