apiVersion: v1
kind: Namespace
metadata:
  name: unityiscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-iscsi-unity-pvc
  namespace: unityiscsi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: unity-iscsi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo
  namespace: unityiscsi
data:
  sample: |
    unity iscsi
    test content
---
apiVersion: v1
kind: Pod
metadata:
  name: unity-iscsi-pod
  namespace: unityiscsi
spec:
  containers:
  - name: task-pv-container
    image: quay.io/centos/centos
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/mnt"
        name: iscsi
      - mountPath: "/tmp"
        name: confmap
    command: ["/bin/bash", "-c", "cp /tmp/keys /mnt/keys && sleep 2000000000"]
  volumes:
    - name: iscsi
      persistentVolumeClaim:
        claimName: dynamic-iscsi-unity-pvc
    - name: confmap
      configMap:
        name: demo
        items:
        - key: sample
          path: keys
