apiVersion: v1
kind: Pod
metadata:
 name: gpu
spec:
 nodeSelector:
    nvidia.com/gpu.product: NVIDIA-A30
 containers:
 - image: nvcr.io/nvidia/tensorflow:19.09-py3
   name: tensorflow
   command: ["/bin/sh","-c"]
   args: ["git clone https://github.com/tensorflow/benchmarks.git;cd benchmarks/scripts/tf_cnn_benchmarks;python3 tf_cnn_benchmarks.py --num_gpus=2 --data_format=NHWC --batch_size=32 --mode
l=resnet50 --variable_update=parameter_server"]
   resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      nvidia.com/gpu: 1
    restartPolicy: Never
