kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lvs-fs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: lvs-fs-sc
  volumeMode: Filesystem

